"""The probe's stand-in for ``commonplace-init``, plus one ordinary command.

The library is the only tree. It mirrors a KB layout: instructions (with each
skill in its own directory there) and types. A normal install places it under
``<environment>/share/cp-delivery-probe/``, a path that survives a change of the
tool's Python version. An editable install reads it from the source tree,
because shared data is copied at install time.

Agents reach the library by reading files, never by running a command.
``cp-delivery-probe-init`` writes three machine-specific, uncommitted outputs
into a project:

- a stub SKILL.md per skill in ``.claude/skills/`` and ``.agents/skills/``, which
  redirects to the real SKILL.md by absolute path;
- ``.cp-delivery-probe/library.md``, giving the library root and entry points as
  full paths (AGENTS.md points to it, CLAUDE.md imports it);
- a Claude Code read rule for the library root in ``.claude/settings.local.json``.

Every command checks those outputs and warns when they no longer match.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from cp_delivery_probe import __version__

SHARE_NAME = "cp-delivery-probe"
STUB_MARKER = ".cp-delivery-probe-stub"
SKILL_DIRS = [".claude/skills", ".agents/skills"]
ROUTING = ".cp-delivery-probe/library.md"
RULE_RECORD = ".cp-delivery-probe/read-rule"
SETTINGS = ".claude/settings.local.json"
GITIGNORE_BEGIN = "# cp-delivery-probe-init begin"
GITIGNORE_END = "# cp-delivery-probe-init end"


def _source_library_dir() -> Path:
    # src/cp_delivery_probe/cli.py -> the package root's library/ directory
    return Path(__file__).resolve().parents[2] / "library"


def _library_dir() -> Path:
    """The library: the source tree for an editable install, else shared data."""
    source = _source_library_dir()
    root = source if (source / "instructions").is_dir() else Path(sys.prefix) / "share" / SHARE_NAME
    if not root.is_dir():
        sys.exit(f"cp-delivery-probe {__version__}: library directory missing at {root}")
    return root.resolve()


def _skills() -> dict[str, Path]:
    """Skill name -> the real skill directory, for every instructions/<name>/SKILL.md."""
    return {p.parent.name: p.parent for p in sorted((_library_dir() / "instructions").glob("*/SKILL.md"))}


def _frontmatter(skill_md: Path) -> str:
    lines = skill_md.read_text().splitlines()
    if not lines or lines[0].strip() != "---":
        sys.exit(f"{skill_md}: no frontmatter")
    return "\n".join(lines[1 : lines.index("---", 1)])


def _render_stub(skill: Path) -> str:
    real = skill / "SKILL.md"
    return (
        f"---\n{_frontmatter(real)}\n---\n\n"
        f"# {skill.name}\n\n"
        "This skill is installed as a stub. Read the real skill at\n\n"
        f"{real}\n\n"
        "and follow it exactly. Resolve every relative link in it against that file's "
        "directory, not this stub's.\n"
    )


def _render_routing() -> str:
    root = _library_dir()
    return (
        "# Delivery-probe library on this machine\n\n"
        "Generated by `cp-delivery-probe-init` for this machine. Do not commit.\n\n"
        f"Library root: {root}\n\n"
        f"- Instructions index: {root / 'instructions' / 'README.md'}\n"
        f"- Types: {root / 'types'}/\n\n"
        "Read library files by full path. Links inside a library file are relative to that file.\n"
    )


def _read_rule() -> str:
    return f"Read(/{_library_dir()}/**)"


def _load_settings(project: Path) -> dict:
    path = project / SETTINGS
    return json.loads(path.read_text()) if path.is_file() else {}


def _statuses(project: Path) -> list[tuple[str, Path]]:
    """(status, output) for every init output. Status: ok, stale, missing, foreign, extra."""
    skills = _skills()
    found = []
    for skill_dir in SKILL_DIRS:
        directory = project / skill_dir
        for name, skill in skills.items():
            dest = directory / name
            if not dest.exists():
                found.append(("missing", dest))
            elif not (dest / STUB_MARKER).is_file():
                found.append(("foreign", dest))
            else:
                current = (dest / "SKILL.md").is_file() and (dest / "SKILL.md").read_text() == _render_stub(skill)
                found.append(("ok" if current else "stale", dest))
        if directory.is_dir():
            for dest in sorted(directory.iterdir()):
                if dest.name not in skills and (dest / STUB_MARKER).is_file():
                    found.append(("extra", dest))
    routing = project / ROUTING
    if not routing.is_file():
        found.append(("missing", routing))
    else:
        found.append(("ok" if routing.read_text() == _render_routing() else "stale", routing))
    allowed = _load_settings(project).get("permissions", {}).get("allow", [])
    settings = project / SETTINGS
    if _read_rule() in allowed:
        found.append(("ok", settings))
    else:
        record = project / RULE_RECORD
        found.append(("stale" if record.is_file() and record.read_text().strip() in allowed else "missing", settings))
    return found


def _warn_on_problems(project: Path) -> None:
    if not (project / ROUTING).parent.is_dir():
        return  # not an initialised project
    problems = [f"{out}: {status}" for status, out in _statuses(project) if status not in ("ok", "foreign")]
    if problems:
        print(
            f"warning: cp-delivery-probe-init outputs do not match this package ({__version__}); "
            "rerun cp-delivery-probe-init:",
            file=sys.stderr,
        )
        for line in problems:
            print(f"  {line}", file=sys.stderr)


def library_root() -> None:
    """Print the library root, for testers. Like every command, check the current project first."""
    _warn_on_problems(Path.cwd())
    print(_library_dir())


def _write_rule(project: Path, remove_only: bool) -> None:
    settings = _load_settings(project)
    allow = settings.setdefault("permissions", {}).setdefault("allow", [])
    record = project / RULE_RECORD
    if record.is_file() and record.read_text().strip() in allow:
        allow.remove(record.read_text().strip())
    if remove_only:
        record.unlink(missing_ok=True)
    else:
        allow.append(_read_rule())
        record.parent.mkdir(exist_ok=True)
        record.write_text(_read_rule() + "\n")
    if not allow:
        del settings["permissions"]["allow"]
    if not settings["permissions"]:
        del settings["permissions"]
    path = project / SETTINGS
    if settings:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(settings, indent=2) + "\n")
    else:
        path.unlink(missing_ok=True)


def _write_gitignore(project: Path, remove_only: bool) -> None:
    path = project / ".gitignore"
    lines = path.read_text().splitlines() if path.is_file() else []
    if GITIGNORE_BEGIN in lines:
        start = lines.index(GITIGNORE_BEGIN)
        del lines[start : lines.index(GITIGNORE_END, start) + 1]
    if not remove_only:
        entries = [f"/{d}/{name}/" for d in SKILL_DIRS for name in _skills()]
        lines += [GITIGNORE_BEGIN, "/.cp-delivery-probe/", f"/{SETTINGS}", *entries, GITIGNORE_END]
    if lines:
        path.write_text("\n".join(lines) + "\n")
    else:
        path.unlink(missing_ok=True)


def init() -> None:
    """Write, check, or remove this package's outputs in one project. Idempotent."""
    parser = argparse.ArgumentParser(prog="cp-delivery-probe-init")
    parser.add_argument("project", nargs="?", default=".", help="project directory (default: current)")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--remove", action="store_true", help="remove everything init wrote")
    action.add_argument("--check", action="store_true", help="report status; exit 1 on problems")
    args = parser.parse_args()
    project = Path(args.project).resolve()
    if args.check:
        statuses = _statuses(project)
        for status, out in statuses:
            print(f"{status}: {out}")
        sys.exit(1 if any(s != "ok" for s, _ in statuses) else 0)
    skills = _skills()
    failed = False
    for status, dest in _statuses(project):
        if dest.name == "library.md" or dest.name == "settings.local.json":
            continue
        if status == "foreign":
            print(f"skipped {dest}: exists and is not a cp-delivery-probe stub", file=sys.stderr)
            failed = True
            continue
        if status != "missing":
            shutil.rmtree(dest)
        if args.remove or status == "extra":
            if status != "missing":
                print(f"removed {dest}")
            continue
        dest.mkdir(parents=True)
        (dest / "SKILL.md").write_text(_render_stub(skills[dest.name]))
        (dest / STUB_MARKER).write_text(__version__ + "\n")
        print(f"wrote stub {dest} -> {skills[dest.name] / 'SKILL.md'}")
    _write_rule(project, args.remove)
    _write_gitignore(project, args.remove)
    routing = project / ROUTING
    if args.remove:
        shutil.rmtree(routing.parent, ignore_errors=True)
        print(f"removed {routing.parent}, the read rule, and the .gitignore block")
    else:
        routing.parent.mkdir(exist_ok=True)
        routing.write_text(_render_routing())
        print(f"wrote {routing}, the read rule {_read_rule()}, and the .gitignore block")
    if failed:
        sys.exit(1)
